In [93]:
import pandas as pd

In [94]:
movies = pd.read_csv("data.txt")

In [84]:
movies.dtypes

User      object
Movie     object
Rating    object
dtype: object

In [95]:
movies

      User          Movie Rating
0    Alice      Star Wars      5
1    Frank  The Godfather      4
2      Bob        Titanic      5
3    Carol     The Matrix      3
4     Dave      Inception      2
5    Emily   Pulp Fiction      4
6   Quincy      Star Wars      5
7      Bob      Star Wars      2
8    Frank   Forrest Gump      3
9    Alice     The Matrix      4
10    Paul        Titanic      4
11   Carol      Inception      5
12    Dave        Titanic      4
13   Emily  The Godfather      5
14   Alice      Inception      3
15    Paul  The Godfather      5
16   Carol   Pulp Fiction      4
17     Ivy      Star Wars      5
18   Emily   Forrest Gump      3
19  Quincy     The Matrix      4
20     Ivy     The Matrix      4
21    Paul      Inception      1
22     Bob  The Godfather      4
23   Frank      Star Wars      5
24     Ivy      Inception      3
25    Dave   Forrest Gump      5
26  Quincy      Inception      3
27   Karen     The Matrix      3
28     Leo        Titanic      4
29     Mia  The Godfather      5
30    Nina      Star Wars      5
31   Oscar     The Matrix      4
32   Sarah      Star Wars     5x
33     Tom   Pulp Fiction   Five
34   Karen      Inception      5
35     Leo      Inception      2
36     Mia   Pulp Fiction      4
37    Nina  The Godfather      4
38   Oscar   Pulp Fiction      2
39   Sarah      Inception      4
40     Tom      Inception    NaN
41  Victor  The Godfather    NaN
42   Wendy   Pulp Fiction      4
43    Zane   Pulp Fiction    3.5
44     Uma        Titanic      5
45  Victor         Matrix      x
46   Wendy     The Matrix    3.5
47  Xander   Forrest Gump      5
48    Yara      Inception     5y
49    Zane   Forrest Gump    3.5
50     Uma      Star Wars     2?
51    Yara     The Matrix    NaN
52   Karen   Pulp Fiction      4
53     Leo   Forrest Gump      5
54     Mia   Forrest Gump      3
55    Nina   Forrest Gump      3
56   Oscar   Forrest Gump      5
57    Zane      Star Wars      4

In [98]:
movies["Clean_Rating"] = movies["Rating"].str.replace("Five", "5", regex=True)
# movies["Clean_Rating"] = movies["Rating"].fillna(0)
movies["Clean_Rating"] = movies["Rating"].str.replace(r'[^0-9,.]', '', regex=True)
# movies["Clean_Rating"] = movies["Clean_Rating"].fillna(0)
# movies["Clean_Rating"] = movies["Clean_Rating"].str.replace("", "0", regex=True)
# movies["Rating"] = movies["Rating"].str.replace('\D', '', regex=True)
# 5x, 5y 2?
movies

      User          Movie Rating Clean_Rating
0    Alice      Star Wars      5            5
1    Frank  The Godfather      4            4
2      Bob        Titanic      5            5
3    Carol     The Matrix      3            3
4     Dave      Inception      2            2
5    Emily   Pulp Fiction      4            4
6   Quincy      Star Wars      5            5
7      Bob      Star Wars      2            2
8    Frank   Forrest Gump      3            3
9    Alice     The Matrix      4            4
10    Paul        Titanic      4            4
11   Carol      Inception      5            5
12    Dave        Titanic      4            4
13   Emily  The Godfather      5            5
14   Alice      Inception      3            3
15    Paul  The Godfather      5            5
16   Carol   Pulp Fiction      4            4
17     Ivy      Star Wars      5            5
18   Emily   Forrest Gump      3            3
19  Quincy     The Matrix      4            4
20     Ivy     The Matrix      4            4
21    Paul      Inception      1            1
22     Bob  The Godfather      4            4
23   Frank      Star Wars      5            5
24     Ivy      Inception      3            3
25    Dave   Forrest Gump      5            5
26  Quincy      Inception      3            3
27   Karen     The Matrix      3            3
28     Leo        Titanic      4            4
29     Mia  The Godfather      5            5
30    Nina      Star Wars      5            5
31   Oscar     The Matrix      4            4
32   Sarah      Star Wars     5x            5
33     Tom   Pulp Fiction   Five
34   Karen      Inception      5            5
35     Leo      Inception      2            2
36     Mia   Pulp Fiction      4            4
37    Nina  The Godfather      4            4
38   Oscar   Pulp Fiction      2            2
39   Sarah      Inception      4            4
40     Tom      Inception    NaN          NaN
41  Victor  The Godfather    NaN          NaN
42   Wendy   Pulp Fiction      4            4
43    Zane   Pulp Fiction    3.5          3.5
44     Uma        Titanic      5            5
45  Victor         Matrix      x
46   Wendy     The Matrix    3.5          3.5
47  Xander   Forrest Gump      5            5
48    Yara      Inception     5y            5
49    Zane   Forrest Gump    3.5          3.5
50     Uma      Star Wars     2?            2
51    Yara     The Matrix    NaN          NaN
52   Karen   Pulp Fiction      4            4
53     Leo   Forrest Gump      5            5
54     Mia   Forrest Gump      3            3
55    Nina   Forrest Gump      3            3
56   Oscar   Forrest Gump      5            5
57    Zane      Star Wars      4            4

In [76]:
movies

      User          Movie Rating
0    Alice      Star Wars      5
1    Frank  The Godfather      4
2      Bob        Titanic      5
3    Carol     The Matrix      3
4     Dave      Inception      2
5    Emily   Pulp Fiction      4
6   Quincy      Star Wars      5
7      Bob      Star Wars      2
8    Frank   Forrest Gump      3
9    Alice     The Matrix      4
10    Paul        Titanic      4
11   Carol      Inception      5
12    Dave        Titanic      4
13   Emily  The Godfather      5
14   Alice      Inception      3
15    Paul  The Godfather      5
16   Carol   Pulp Fiction      4
17     Ivy      Star Wars      5
18   Emily   Forrest Gump      3
19  Quincy     The Matrix      4
20     Ivy     The Matrix      4
21    Paul      Inception      1
22     Bob  The Godfather      4
23   Frank      Star Wars      5
24     Ivy      Inception      3
25    Dave   Forrest Gump      5
26  Quincy      Inception      3
27   Karen     The Matrix      3
28     Leo        Titanic      4
29     Mia  The Godfather      5
30    Nina      Star Wars      5
31   Oscar     The Matrix      4
32   Sarah      Star Wars     5x
33     Tom   Pulp Fiction   Five
34   Karen      Inception      5
35     Leo      Inception      2
36     Mia   Pulp Fiction      4
37    Nina  The Godfather      4
38   Oscar   Pulp Fiction      2
39   Sarah      Inception      4
40     Tom      Inception    NaN
41  Victor  The Godfather    NaN
42   Wendy   Pulp Fiction      4
43    Zane   Pulp Fiction    3.5
44     Uma        Titanic      5
45  Victor         Matrix      x
46   Wendy     The Matrix    3.5
47  Xander   Forrest Gump      5
48    Yara      Inception     5y
49    Zane   Forrest Gump    3.5
50     Uma      Star Wars     2?
51    Yara     The Matrix    NaN
52   Karen   Pulp Fiction      4
53     Leo   Forrest Gump      5
54     Mia   Forrest Gump      3
55    Nina   Forrest Gump      3
56   Oscar   Forrest Gump      5
57    Zane      Star Wars      4